export type FeeItem = {
  id: string;
  category: string;
  name: string;
  price: number | null;
  unit?: string;
  note?: string;
  stairRate?: number;
};

export const products: FeeItem[] = [
  { id: "tv32", category: "電視", name: "液晶電視 32 吋（含）以下", price: 300, unit: "台", stairRate: 50 },
  { id: "tv33", category: "電視", name: "液晶電視 33–49 吋", price: 450, unit: "台", stairRate: 50 },
  { id: "tv50", category: "電視", name: "液晶電視 50–54 吋", price: 550, unit: "台", stairRate: 50 },
  { id: "tv55", category: "電視", name: "液晶電視 55–59 吋", price: 600, unit: "台", stairRate: 100 },
  { id: "tv60", category: "電視", name: "液晶電視 60–74 吋", price: 700, unit: "台", stairRate: 100 },
  { id: "tv75", category: "電視", name: "液晶電視 75 吋（含）以上", price: 1300, unit: "台", stairRate: 100 },
  { id: "theater-delivery", category: "影音", name: "家庭劇院／卡拉 OK｜只送不裝", price: 300, unit: "組", note: "含拆箱、定位、測試" },
  { id: "washer12", category: "洗衣", name: "洗衣機 12.5 公斤（含）以下", price: 300, unit: "台", stairRate: 50 },
  { id: "washer18", category: "洗衣", name: "洗衣機 13–18 公斤（含）", price: 400, unit: "台", stairRate: 100 },
  { id: "washer19", category: "洗衣", name: "洗衣機 19 公斤（含）以上", price: 500, unit: "台", stairRate: 100 },
  { id: "tower-delivery", category: "洗衣", name: "上乾下洗洗衣機（洗衣塔／一體成形）｜只送不裝", price: 800, unit: "台", stairRate: 100 },
  { id: "tower", category: "洗衣", name: "上乾下洗洗衣機（洗衣塔／一體成形）｜運送含基本安裝", price: 2700, unit: "台", stairRate: 100 },
  { id: "front13", category: "洗衣", name: "滾筒洗衣機 13 公斤（含）以下", price: 600, unit: "台", stairRate: 50 },
  { id: "front16", category: "洗衣", name: "滾筒洗衣機 14–16 公斤", price: 700, unit: "台", stairRate: 100 },
  { id: "front17", category: "洗衣", name: "滾筒洗衣機 17 公斤（含）以上", price: 750, unit: "台", stairRate: 100 },
  { id: "lg-mini", category: "洗衣", name: "LG 下洗迷你洗衣機", price: 300, unit: "台", stairRate: 50 },
  { id: "dryer10", category: "洗衣", name: "乾衣機 10 公斤（含）以下", price: 250, unit: "台" },
  { id: "dryer11", category: "洗衣", name: "乾衣機 11 公斤（含）以上", price: 300, unit: "台" },
  { id: "heat-dryer", category: "洗衣", name: "免曬衣乾衣機", price: 500, unit: "台" },
  { id: "fridge100", category: "冰箱", name: "冰箱／冷凍櫃 100 公升（含）以下", price: 200, unit: "台", stairRate: 50 },
  { id: "fridge199", category: "冰箱", name: "冰箱／冷凍櫃 101–199 公升", price: 250, unit: "台", stairRate: 50 },
  { id: "fridge299", category: "冰箱", name: "冰箱／冷凍櫃 200–299 公升", price: 300, unit: "台", stairRate: 50 },
  { id: "fridge399", category: "冰箱", name: "冰箱／冷凍櫃 300–399 公升", price: 450, unit: "台", stairRate: 100 },
  { id: "fridge499", category: "冰箱", name: "冰箱／冷凍櫃 400–499 公升", price: 500, unit: "台", stairRate: 100 },
  { id: "fridge599", category: "冰箱", name: "冰箱／冷凍櫃 500–599 公升", price: 700, unit: "台", stairRate: 100 },
  { id: "fridge600", category: "冰箱", name: "冰箱／冷凍櫃 600 公升（含）以上", price: 900, unit: "台", stairRate: 100 },
  { id: "side-fridge", category: "冰箱", name: "對開冰箱", price: 1200, unit: "台", stairRate: 100 },
  { id: "knock-fridge", category: "冰箱", name: "LG 敲敲門冰箱", price: 1500, unit: "台", stairRate: 100 },
  { id: "styler", category: "冰箱", name: "電子衣櫥", price: 600, unit: "台" },
  { id: "hood", category: "小型家電", name: "排油煙機／瓦斯爐／熱水器", price: 300, unit: "件", note: "運送、拆箱，不含安裝" },
  { id: "drybox", category: "小型家電", name: "電子防潮箱", price: 300, unit: "件", note: "運送、拆箱，不含安裝" },
  { id: "small-appliance", category: "小型家電", name: "水冷扇／除濕機／烘碗機等", price: 300, unit: "件", note: "運送、拆箱、定位，不含安裝" },
];

export const splitAC: FeeItem[] = [
  { id: "split36", category: "分離式冷氣", name: "1 對 1｜3.6 kW 以下（含）", price: 3100, unit: "組", stairRate: 100 },
  { id: "split41", category: "分離式冷氣", name: "1 對 1｜3.7–4.1 kW", price: 3500, unit: "組", stairRate: 100 },
  { id: "split52", category: "分離式冷氣", name: "1 對 1｜4.2–5.2 kW", price: 3900, unit: "組", stairRate: 100 },
  { id: "split65", category: "分離式冷氣", name: "1 對 1｜5.3–6.5 kW", price: 4500, unit: "組", stairRate: 100 },
  { id: "split72", category: "分離式冷氣", name: "1 對 1｜6.6–7.2 kW", price: 5000, unit: "組", stairRate: 100 },
  { id: "split91", category: "分離式冷氣", name: "1 對 1｜7.3–9.1 kW", price: 6000, unit: "組", stairRate: 100 },
  { id: "split116", category: "分離式冷氣", name: "1 對 1｜9.2–11.6 kW", price: 8000, unit: "組", stairRate: 100 },
  { id: "split117", category: "分離式冷氣", name: "1 對 1｜11.7 kW 以上", price: 9200, unit: "組", stairRate: 100 },
  { id: "multi12", category: "分離式冷氣", name: "1 對 2｜不限 kW", price: 5000, unit: "組", note: "以 10 米為限；超出由顧客付費", stairRate: 150 },
  { id: "multi13", category: "分離式冷氣", name: "1 對 3｜不限 kW", price: 5000, unit: "組", note: "以 10 米為限；超出由顧客付費；1 對 4 樓層費再依表類推", stairRate: 200 },
];

export const windowAC: FeeItem[] = [
  { id: "window32", category: "窗型冷氣", name: "窗型／直立式｜3.2 kW（含）以下", price: 800, unit: "台", stairRate: 100 },
  { id: "window53", category: "窗型冷氣", name: "窗型／直立式｜3.21–5.3 kW", price: 1000, unit: "台", stairRate: 100 },
  { id: "window54", category: "窗型冷氣", name: "窗型／直立式｜超過 5.3 kW", price: 1200, unit: "台", stairRate: 100 },
  { id: "mobile", category: "窗型冷氣", name: "移動式冷氣", price: 800, unit: "台" },
];

export const extras: FeeItem[] = [
  { id: "door", category: "一般加項", name: "拆卸大門／室內門／過窗", price: 200, unit: "次" },
  { id: "fridge-door", category: "一般加項", name: "冰箱門拆裝（兩片門板）", price: 300, unit: "台", note: "每超出一片加收 150 元" },
  { id: "washer-stack", category: "一般加項", name: "滾筒洗衣機堆疊免曬衣乾衣機", price: 2000, unit: "組" },
  { id: "tv-own-fixed42", category: "電視壁掛", name: "平面固定式｜42 吋以下", price: 800, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-fixed59", category: "電視壁掛", name: "平面固定式｜43–59 吋", price: 1000, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-fixed65", category: "電視壁掛", name: "平面固定式｜60–65 吋", price: 1700, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-fixed66", category: "電視壁掛", name: "平面固定式｜66 吋以上", price: 2000, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-tilt42", category: "電視壁掛", name: "上下仰角式｜42 吋以下", price: 1100, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-tilt59", category: "電視壁掛", name: "上下仰角式｜43–59 吋", price: 1300, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-tilt65", category: "電視壁掛", name: "上下仰角式｜60–65 吋", price: 1500, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-tilt66", category: "電視壁掛", name: "上下仰角式｜66 吋以上", price: 2000, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-own-arm", category: "電視壁掛", name: "懸臂式／雙臂規格｜所有尺寸", price: 1500, unit: "台", note: "僅安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-kit-fixed55", category: "電視壁掛", name: "平面固定式｜32–55 吋", price: 1500, unit: "台", note: "壁掛架＋安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-kit-fixed56", category: "電視壁掛", name: "平面固定式｜56 吋以上", price: 2500, unit: "台", note: "壁掛架＋安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-kit-tilt", category: "電視壁掛", name: "上下仰角式", price: null, unit: "台", note: "現場報價；適用水泥牆面，特殊牆面另議" },
  { id: "tv-kit-arm69", category: "電視壁掛", name: "懸臂式／雙臂規格｜32–69 吋", price: 3500, unit: "台", note: "壁掛架＋安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-kit-arm70", category: "電視壁掛", name: "懸臂式／雙臂規格｜70 吋以上", price: 4500, unit: "台", note: "壁掛架＋安裝費；適用水泥牆面，特殊牆面另議" },
  { id: "tv-existing", category: "電視壁掛", name: "既有壁掛架安裝費", price: 300, unit: "台" },
  { id: "tv-special-wall", category: "電視壁掛", name: "特殊施工／洗洞｜文化石、大理石等", price: null, unit: "次", note: "使用安全合規材質，現場報價" },
  { id: "cable", category: "電視安裝", name: "室內 CABLE 線（超過 3 米）", price: 30, unit: "米" },
  { id: "antenna", category: "電視安裝", name: "一般 UHF／VHF 室外天線（五樓以下）", price: 1500, unit: "組" },
  { id: "ac-remove-recycle", category: "分離式冷氣", name: "分離式拆舊機（舊機交由人員回收）", price: 0, unit: "組", note: "舊機交由安裝人員免費回收，免收拆機工資（危險施工另計）" },
  { id: "ac-remove11", category: "分離式冷氣", name: "分離式拆舊機（顧客自留舊機）｜1 對 1", price: 1000, unit: "組", note: "交由安裝人員回收免收拆機工資（NT$ 0）；顧客自行保留舊機才收費" },
  { id: "ac-remove12", category: "分離式冷氣", name: "分離式拆舊機（顧客自留舊機）｜1 對 2", price: 1500, unit: "組", note: "交由安裝人員回收免收拆機工資（NT$ 0）；顧客自行保留舊機才收費" },
  { id: "pipe23", category: "分離式冷氣", name: "被覆銅管延長｜2”3”", price: 400, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "pipe24", category: "分離式冷氣", name: "被覆銅管延長｜2”4”", price: 500, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "pipe25", category: "分離式冷氣", name: "被覆銅管延長｜2”5”", price: 550, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "pipe35", category: "分離式冷氣", name: "被覆銅管延長｜3”5”", price: 600, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "pipe36", category: "分離式冷氣", name: "被覆銅管延長｜3”6”", price: 600, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "pipe47", category: "分離式冷氣", name: "被覆銅管延長｜4”7”", price: 700, unit: "公尺", note: "限用 8mm 以上厚度" },
  { id: "flush", category: "分離式冷氣", name: "延用舊管洗管（R141V）", price: 3000, unit: "次" },
  { id: "duct80", category: "分離式冷氣", name: "銅管管槽 80／100", price: 300, unit: "公尺" },
  { id: "duct120", category: "分離式冷氣", name: "銅管管槽 120／140", price: 600, unit: "公尺" },
  { id: "duct-part80", category: "分離式冷氣", name: "管槽配件 80／100", price: 400, unit: "件" },
  { id: "duct-part120", category: "分離式冷氣", name: "管槽配件 120／140", price: 600, unit: "件" },
  { id: "refrigerant", category: "分離式冷氣", name: "R32／R410 整台冷媒填充", price: 1200, unit: "台" },
  { id: "refrigerant-leak", category: "分離式冷氣", name: "R32／R410 冷媒填充（含補漏）", price: 2500, unit: "台" },
  { id: "hole25", category: "冷氣共用", name: "洗孔｜牆厚 25 公分以內", price: 800, unit: "孔" },
  { id: "hole40", category: "冷氣共用", name: "洗孔｜牆厚 40 公分內", price: 1000, unit: "孔" },
  { id: "holewood", category: "冷氣共用", name: "洗孔｜木板牆 3 分板以上", price: 300, unit: "孔" },
  { id: "drain", category: "冷氣共用", name: "4 分透明排水管", price: 30, unit: "米", note: "一層樓以上另有 100 元／樓層" },
  { id: "pump-normal", category: "冷氣共用", name: "排水器｜一般型（含安裝）", price: 1600, unit: "個" },
  { id: "pump-quiet", category: "冷氣共用", name: "排水幫浦｜靜音型", price: 2000, unit: "個" },
  { id: "galv-small", category: "冷氣共用", name: "鍍鋅豪華架｜小組 80 公分", price: 1000, unit: "組" },
  { id: "galv-medium", category: "冷氣共用", name: "鍍鋅豪華架｜中組 90 公分", price: 1200, unit: "組" },
  { id: "galv-large", category: "冷氣共用", name: "鍍鋅豪華架｜大組 100 公分", price: 1500, unit: "組" },
  { id: "steel-small", category: "冷氣共用", name: "不鏽鋼組合架｜小組 80 公分", price: 3000, unit: "組" },
  { id: "steel-large", category: "冷氣共用", name: "不鏽鋼組合架｜大組 100 公分", price: 3500, unit: "組" },
  { id: "floor-rack", category: "冷氣共用", name: "室外機塑鋼落地架", price: 800, unit: "組" },
  { id: "socket", category: "冷氣共用", name: "電源插座", price: 200, unit: "組", note: "隨機有附則免收" },
  { id: "plug", category: "冷氣共用", name: "插頭", price: 200, unit: "組" },
  { id: "box", category: "冷氣共用", name: "冷氣插座盒", price: 400, unit: "個" },
  { id: "wire20", category: "冷氣共用", name: "電源線／控制線 2.0mm", price: 60, unit: "公尺", note: "甲方得按市場行情調整" },
  { id: "wire35", category: "冷氣共用", name: "電源線／控制線 3.5mm", price: 75, unit: "公尺", note: "甲方得按市場行情調整" },
  { id: "wire55", category: "冷氣共用", name: "電源線／控制線 5.5mm", price: 90, unit: "公尺", note: "甲方得按市場行情調整" },
  { id: "panel", category: "冷氣共用", name: "加裝分電表（電源線另計）", price: 2000, unit: "個" },
  { id: "breaker", category: "冷氣共用", name: "無熔絲開關 30A–2P", price: 500, unit: "個", note: "不含開關箱" },
  { id: "window-remove-recycle", category: "窗型冷氣", name: "窗型冷氣拆舊機（舊機交由人員回收）", price: 0, unit: "台", note: "舊機交由安裝人員免費回收，免收拆機工資（危險施工另計）" },
  { id: "window-remove-self", category: "窗型冷氣", name: "窗型冷氣拆舊機（顧客自留舊機）", price: 500, unit: "台", note: "交由安裝人員回收免收拆機工資（NT$ 0）；顧客自行保留舊機才收費" },
  { id: "window-frame", category: "窗型冷氣", name: "下鋁窗安裝上緣加框架", price: 1000, unit: "台" },
  { id: "window-enlarge", category: "窗型冷氣", name: "框加大", price: 300, unit: "台", note: "敲水泥牆另議" },
  { id: "window-hang", category: "窗型冷氣", name: "窗型冷氣懸掛式施工", price: 2500, unit: "台" },
  { id: "window-cover", category: "窗型冷氣", name: "冷氣窗口封板", price: 300, unit: "窗" },
  { id: "awning-small", category: "冷氣共用", name: "塑鋼遮雨篷｜小組", price: 1200, unit: "組" },
  { id: "awning-large", category: "冷氣共用", name: "塑鋼遮雨篷｜大組", price: 1500, unit: "組" },
  { id: "iron-hollow", category: "冷氣共用", name: "剪鋁／鐵窗｜中空", price: 300, unit: "窗" },
  { id: "iron-solid", category: "冷氣共用", name: "剪鋁／鐵窗｜實心", price: 600, unit: "窗" },
  { id: "steel-window", category: "冷氣共用", name: "剪不鏽鋼窗", price: 600, unit: "窗" },
];

export const areaFees: Record<string, { price: number | null; places: string }> = {
  "0": { price: 0, places: "高雄市（舊）、鳳山市、大寮" },
  "100": { price: 100, places: "楠梓、旗津" },
  "200": { price: 200, places: "橋頭、林園、九曲堂、彌陀、大樹、燕巢、梓官、岡山、大社" },
  "300": { price: 300, places: "屏東市、萬丹、新園、路竹、永安" },
  "400": { price: 400, places: "田寮、中寮、麟洛、竹田、崁頂、東港" },
  "500": { price: 500, places: "內門、旗山、阿蓮、湖內、大湖、高樹、里港、九如、林邊" },
  "600": { price: 600, places: "杉林、美濃、內埔、潮州、新碑" },
  "700": { price: 700, places: "甲仙、六龜、三地門、鹽埔、萬巒" },
  "800": { price: 800, places: "涼山、佳平、來義、佳冬" },
  "900": { price: 900, places: "枋寮" },
  "1500": { price: 1500, places: "三民、桃源、茂林、霧台、枋山、牡丹、車城、恆春" },
  "2000": { price: 2000, places: "滿洲" },
};
